// lib/worktrees.mjs — per-task git worktree + lease isolation. ORCH-077..083.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export function runGit(cwd, args) {
  return execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString();
}

// A reference (non-bare) clone is the git database we attach worktrees to.
export function ensureRepo(repoSlug, reposRoot, base = 'https://github.com') {
  const name = repoSlug.split('/').pop();
  const dir = join(reposRoot, name);
  if (existsSync(join(dir, '.git'))) return dir;
  mkdirSync(reposRoot, { recursive: true });
  runGit(reposRoot, ['clone', '--quiet', `${base}/${repoSlug}.git`, dir]);
  return dir;
}

export function fetchLatest(sourceRepo, branch = '--all') {
  runGit(sourceRepo, ['fetch', '--quiet', 'origin', ...(branch === '--all' ? ['--all'] : [branch])]);
}

export function createWorktree({ sourceRepo, worktreeRoot, taskId, baseSha }) {
  mkdirSync(worktreeRoot, { recursive: true });
  const dest = join(worktreeRoot, taskId);
  const args = ['worktree', 'add', '--detach', dest];
  args.push(baseSha || 'HEAD');
  runGit(sourceRepo, args);
  return dest;
}

export function removeWorktree({ sourceRepo, worktreeRoot, taskId }) {
  const dest = join(worktreeRoot, taskId);
  if (!existsSync(dest)) return;
  try { runGit(sourceRepo, ['worktree', 'remove', '--force', dest]); }
  catch { runGit(sourceRepo, ['worktree', 'prune']); }
}

// Resolve the real git dir for a worktree (its .git may be a "gitdir:" pointer).
export function resolveGitDir(worktreePath) {
  const dotgit = join(worktreePath, '.git');
  if (!existsSync(dotgit)) return null;
  const st = readFileSync(dotgit, 'utf8');
  const m = st.match(/^gitdir:\s*(.+)$/m);
  return m ? join(worktreePath, m[1].trim()) : dotgit;
}

const PUSH_GUARD = `#!/bin/sh
# Generated by the Sonoran router — block pushes touching paths outside the
# task's allowed set (ORCH-082). Edit .sonoran-allowed-paths to adjust.
allowed=".sonoran-allowed-paths"
[ -f "$allowed" ] || exit 0
while read -r local_ref local_sha remote_ref remote_sha; do
  files=$(git diff --name-only "$remote_sha"..."$local_sha" 2>/dev/null)
  for f in $files; do
    ok=0
    while IFS= read -r pat; do
      [ -z "$pat" ] && continue
      case "$f" in
        $pat) ok=1; break ;;
      esac
    done < "$allowed"
    if [ "$ok" = 0 ]; then
      echo "push blocked: '$f' is outside this task's allowed paths" >&2
      exit 1
    fi
  done
done
exit 0
`;

// Install a pre-push guard into the worktree's actual git dir (best-effort).
export function installPushGuard(worktreePath, allowedPaths = []) {
  const gitdir = resolveGitDir(worktreePath);
  if (!gitdir) return;
  writeFileSync(join(worktreePath, '.sonoran-allowed-paths'), allowedPaths.join('\n') + '\n');
  const hooksDir = join(gitdir, 'hooks');
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(join(hooksDir, 'pre-push'), PUSH_GUARD, { mode: 0o755 });
}
