// lib/worktrees.mjs — per-task git worktree + lease isolation. ORCH-077..083.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export function runGit(cwd, args) {
  return execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString();
}

// A reference (non-bare) clone is the git database we attach worktrees to.
export function ensureRepo(repoSlug, reposRoot, base = 'https://github.com') {
  const name = repoSlug.split('/').pop();
  const dir = join(reposRoot, name);
  if (existsSync(join(dir, '.git'))) return dir;
  mkdirSync(reposRoot, { recursive: true });
  runGit(reposRoot, ['clone', '--quiet', `${base}/${repoSlug}.git`, dir]);
  return dir;
}

export function fetchLatest(sourceRepo, branch = '--all') {
  runGit(sourceRepo, ['fetch', '--quiet', 'origin', ...(branch === '--all' ? ['--all'] : [branch])]);
}

export function createWorktree({ sourceRepo, worktreeRoot, taskId, baseSha }) {
  mkdirSync(worktreeRoot, { recursive: true });
  const dest = join(worktreeRoot, taskId);
  const args = ['worktree', 'add', '--detach', dest];
  args.push(baseSha || 'HEAD');
  runGit(sourceRepo, args);
  return dest;
}

export function removeWorktree({ sourceRepo, worktreeRoot, taskId }) {
  const dest = join(worktreeRoot, taskId);
  if (!existsSync(dest)) return;
  try { runGit(sourceRepo, ['worktree', 'remove', '--force', dest]); }
  catch { runGit(sourceRepo, ['worktree', 'prune']); }
}

// Resolve the real git dir for a worktree (its .git may be a "gitdir:" pointer).
export function resolveGitDir(worktreePath) {
  const dotgit = join(worktreePath, '.git');
  if (!existsSync(dotgit)) return null;
  const st = readFileSync(dotgit, 'utf8');
  const m = st.match(/^gitdir:\s*(.+)$/m);
  return m ? join(worktreePath, m[1].trim()) : dotgit;
}

const PUSH_GUARD = `#!/bin/sh
# Generated by the Sonoran router — enforce base-SHA and allowed-path scope on push (ORCH-081/082).
allowed=".sonoran-allowed-paths"
base_file=".sonoran-base-sha"
[ -f "$base_file" ] && base_sha="$(tr -d '[:space:]' < "$base_file")" || base_sha=""
zero="0000000000000000000000000000000000000000"

while read -r local_ref local_sha remote_ref remote_sha; do
  # base-SHA gate: block if the remote branch tip moved from the recorded base
  if [ -n "$base_sha" ] && [ -n "$remote_sha" ] && [ "$remote_sha" != "$zero" ] && [ "$remote_sha" != "$base_sha" ]; then
    echo "push blocked: branch moved from recorded base ($base_sha) to $remote_sha" >&2
    exit 1
  fi

  # allowed-paths gate
  if [ -f "$allowed" ]; then
    files=$(git diff --name-only "$remote_sha"..."$local_sha" 2>/dev/null)
    for f in $files; do
      ok=0
      while IFS= read -r pat; do
        [ -z "$pat" ] && continue
        case "$f" in
          $pat) ok=1; break ;;
        esac
      done < "$allowed"
      if [ "$ok" = 0 ]; then
        echo "push blocked: '$f' is outside this task's allowed paths" >&2
        exit 1
      fi
    done
  fi
done
exit 0
`;

// Install a pre-push guard into the worktree's actual git dir (best-effort).
export function installPushGuard(worktreePath, { allowedPaths = [], baseSha = '' } = {}) {
  const gitdir = resolveGitDir(worktreePath);
  if (!gitdir) return;
  writeFileSync(join(worktreePath, '.sonoran-allowed-paths'), allowedPaths.join('\n') + '\n');
  if (baseSha) {
    writeFileSync(join(worktreePath, '.sonoran-base-sha'), baseSha + '\n');
  }
  const hooksDir = join(gitdir, 'hooks');
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(join(hooksDir, 'pre-push'), PUSH_GUARD, { mode: 0o755 });
}

// Remove a worktree by explicit source repo + path (used by the lease reaper).
export function removeWorktreePath(sourceRepo, worktreePath) {
  if (!existsSync(worktreePath)) return;
  try { runGit(sourceRepo, ['worktree', 'remove', '--force', worktreePath]); }
  catch { runGit(sourceRepo, ['worktree', 'prune']); }
}
