// lib/worktrees.mjs — per-task git worktree + lease isolation. ORCH-077..083.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export function runGit(cwd, args) {
  return execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString();
}

// A reference (non-bare) clone is the git database we attach worktrees to.
export function ensureRepo(repoSlug, reposRoot, base = 'https://github.com') {
  const name = repoSlug.split('/').pop();
  const dir = join(reposRoot, name);
  if (existsSync(join(dir, '.git'))) return dir;
  mkdirSync(reposRoot, { recursive: true });
  runGit(reposRoot, ['clone', '--quiet', `${base}/${repoSlug}.git`, dir]);
  return dir;
}

export function fetchLatest(sourceRepo, branch = '--all') {
  runGit(sourceRepo, ['fetch', '--quiet', 'origin', ...(branch === '--all' ? ['--all'] : [branch])]);
}

// Resolve + verify a nonempty base SHA for a task BEFORE any worktree is created.
// - If `providedSha` is given (event/base context or the envelope), it must resolve
//   to a real commit object in the clone; short SHAs are expanded to full.
// - Otherwise resolve the branch tip for `baseRef` from the remote.
// Returns the full SHA (40 hex) or null if it cannot be resolved/verified. The
// router refuses to launch a code task when this returns null.
export function resolveBaseSha(sourceRepo, baseRef, { providedSha = '' } = {}) {
  if (!sourceRepo || !baseRef) return null;
  try { runGit(sourceRepo, ['fetch', '--quiet', 'origin', '--all']); } catch { /* best effort */ }
  const target = providedSha ? `${providedSha}^{commit}` : `refs/heads/${baseRef}`;
  try {
    const sha = runGit(sourceRepo, ['rev-parse', '--verify', target]).trim();
    if (!sha || !/^[0-9a-f]{40}$/i.test(sha)) return null;
    return sha;
  } catch {
    return null;
  }
}

// A git ref name must be path-safe and never a CLI flag. We reject anything that
// isn't a conservative `[A-Za-z0-9._/-]` token, so envelope-supplied branch names
// can never become argument injection for `git worktree add`.
const BRANCH_RE = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;
export function safeBranchName(name) {
  if (!name) return '';
  const s = String(name).trim();
  if (!s) return '';
  if (!BRANCH_RE.test(s)) return '';
  if (s.startsWith('-') || s.startsWith('/') || s.endsWith('/') || s.endsWith('.')) return '';
  if (s.includes('..') || s.includes('//') || /\.lock$/i.test(s)) return '';
  return s;
}

// Create one named branch + worktree per task (ORCH-077..080). Ownership becomes
// task <=> branch <=> worktree <=> lease, so the worker commits to a real branch
// instead of a detached commit it has to turn into a branch itself.
export function createWorktree({ sourceRepo, worktreeRoot, taskId, baseSha, branch }) {
  const dest = join(worktreeRoot, taskId);
  if (existsSync(dest)) return dest; // idempotent on retry: reuse existing worktree
  mkdirSync(worktreeRoot, { recursive: true });
  const safeBranch = safeBranchName(branch) || `agent/${taskId}`;
  try {
    runGit(sourceRepo, ['worktree', 'add', '-b', safeBranch, dest, baseSha || 'HEAD']);
  } catch {
    // Branch already exists (e.g. a prior attempt on a re-delivered task) — attach to it.
    // Fail closed: if attach also fails we must NOT silently fall back to detached HEAD.
    runGit(sourceRepo, ['worktree', 'add', dest, safeBranch]);
  }
  return dest;
}

export function removeWorktree({ sourceRepo, worktreeRoot, taskId }) {
  const dest = join(worktreeRoot, taskId);
  if (!existsSync(dest)) return;
  try { runGit(sourceRepo, ['worktree', 'remove', '--force', dest]); }
  catch { runGit(sourceRepo, ['worktree', 'prune']); }
}

// Resolve the real git dir for a worktree (its .git may be a "gitdir:" pointer).
export function resolveGitDir(worktreePath) {
  const dotgit = join(worktreePath, '.git');
  if (!existsSync(dotgit)) return null;
  const st = readFileSync(dotgit, 'utf8');
  const m = st.match(/^gitdir:\s*(.+)$/m);
  return m ? join(worktreePath, m[1].trim()) : dotgit;
}

const PUSH_GUARD = `#!/bin/sh
# Generated by the Sonoran router — enforce base-ref movement + allowed-path scope on push (ORCH-081/082).
# The base-branch movement check is intentionally separate from the pushed ref:
# a brand-new feature branch has an all-zero remote SHA, so comparing that against
# the recorded base SHA would wrongly allow a push after the base moved. Instead we
# ask the remote for the base branch's CURRENT tip and compare it to the recorded
# base SHA. Only the base branch's unexpected movement blocks a push.
allowed=".sonoran-allowed-paths"
base_ref="$(cat .sonoran-base-ref 2>/dev/null | tr -d '[:space:]')"
base_sha="$(cat .sonoran-base-sha 2>/dev/null | tr -d '[:space:]')"
zero="0000000000000000000000000000000000000000"
# Normalize to a full ref path so both the remote query and the "don't push to base"
# comparison work whether we stored "main" or "refs/heads/main".
case "$base_ref" in
  refs/heads/*) base_full="$base_ref" ;;
  *) base_full="refs/heads/$base_ref" ;;
esac

warn() { echo "$*" >&2; }
block() { warn "push blocked: $*"; exit 1; }

# 1. Base-ref movement gate (ORCH-081): the task's base branch must still be at the
#    recorded SHA on the remote. Checked independently of whatever is being pushed.
if [ -n "$base_ref" ] && [ -n "$base_sha" ]; then
  remote_base="$(git ls-remote origin "$base_full" 2>/dev/null | awk '{print $1}')"
  if [ -z "$remote_base" ]; then
    block "base branch $base_full not found on remote (ref deleted or moved?)"
  elif [ "$remote_base" != "$base_sha" ]; then
    block "base branch moved unexpectedly: $base_full is at $remote_base, expected $base_sha"
  fi
fi

while read -r local_ref local_sha remote_ref remote_sha; do
  # 2. A worker stays on its own branch; never let a push move the base branch itself.
  if [ -n "$base_ref" ] && [ "$remote_ref" = "$base_full" ]; then
    block "cannot push directly to the base branch ($base_full)"
  fi

  # 3. Allowed-paths gate (ORCH-082).
  if [ -f "$allowed" ]; then
    old="$remote_sha"
    [ "$old" = "$zero" ] && old="$base_sha"
    files=$(git diff --name-only "$old"..."$local_sha" 2>/dev/null)
    for f in $files; do
      ok=0
      while IFS= read -r pat; do
        [ -z "$pat" ] && continue
        case "$f" in
          $pat) ok=1; break ;;
        esac
      done < "$allowed"
      if [ "$ok" = 0 ]; then
        block "'$f' is outside this task's allowed paths"
      fi
    done
  fi
done
exit 0
`;

// Install a pre-push guard into the worktree's actual git dir (best-effort).
export function installPushGuard(worktreePath, { allowedPaths = [], baseSha = '', baseRef = '' } = {}) {
  const gitdir = resolveGitDir(worktreePath);
  if (!gitdir) return;
  writeFileSync(join(worktreePath, '.sonoran-allowed-paths'), (allowedPaths || []).join('\n') + '\n');
  if (baseSha) {
    writeFileSync(join(worktreePath, '.sonoran-base-sha'), baseSha + '\n');
  }
  if (baseRef) {
    writeFileSync(join(worktreePath, '.sonoran-base-ref'), baseRef + '\n');
  }
  const hooksDir = join(gitdir, 'hooks');
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(join(hooksDir, 'pre-push'), PUSH_GUARD, { mode: 0o755 });
}

// Remove a worktree by explicit source repo + path (used by the lease reaper).
export function removeWorktreePath(sourceRepo, worktreePath) {
  if (!existsSync(worktreePath)) return;
  try { runGit(sourceRepo, ['worktree', 'remove', '--force', worktreePath]); }
  catch { runGit(sourceRepo, ['worktree', 'prune']); }
}
